---
abstract: 'Automatically creates a GraphViz2 visualisation of a map'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::NoTabs: '0'
configure_requires:
  Module::Build::Tiny: '0.039'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-MapMetro-MakeGraphViz
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dist::Zilla: '5.000'
  GraphViz2: '0'
  Map::Metro: '0.2000'
  Moose: '2.0000'
  Path::Tiny: '0'
  Types::Standard: '0'
  namespace::sweep: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/Csson/p5-Dist-Zilla-Plugin-mapMetro-MakeGraphViz/issues
  homepage: https://github.com/Csson/p5-Dist-Zilla-Plugin-mapMetro-MakeGraphViz
  repository: https://github.com/Csson/p5-Dist-Zilla-Plugin-mapMetro-MakeGraphViz.git
version: '0.1000'
